### PR TITLE
Ss/toolbar update to allow easier inclusion of 3rd party buttons & actions

### PR DESCRIPTION
**Pull request by obct537**

### CODE REVIEW

**Comment by obct537** [comment]
@tkimnguyen finally getting around to responding to your comments above. Any particular place I should add docs for that? This is a very technical, non-user-friendly system, the current readme doesn't seem to be geared towards that.

**Comment by obct537** [comment]
as for testing, testing JS is a small nightmare. We need them ROBOT tests!

**Comment by tkimnguyen** [comment]
@obct537 re docs you could add a new file e.g. developer.rst ?

**Comment by vangheem** [comment]
@obct537 could you take a few minutes to rebase this and add some notes to developer.rst?

**Pull request merged**
