### PR TITLE
WIP: Plone 5.1

### PR DESCRIPTION
**Pull request by tkimnguyen**

### CODE REVIEW

**Comment by vangheem** [comment]
Seems to me we should leapfrog 5.1 and go directly to 5.2 at this point and spend all major change effort around also the python 3 migration.

I'm closing this. Kim, please reopen if you disagree!

**Comment by tkimnguyen** [comment]
Eek maybe but isn’t that a ton more work?

**Comment by vangheem** [comment]
I've done quite a bit of python 2 -> 3 migrations at this point and it's really not that hard...

**Comment by tkimnguyen** [comment]
Ok

**Pull request closed without merging**
