### PR TITLE
Add buildout and instructions for running a dev instance

### PR DESCRIPTION
**Pull request by davisagli**
This adds a buildout to set up an instance and celery worker, along with instructions for macOS.

I also removed bootstrap.py in favor of installing zc.buildout and cryptography using pip, because the bootstrap script was not working for me.

### CODE REVIEW

**Comment by tkimnguyen** [comment]
Thanks David! I'm trying this out on a MacOS 10.12.4 but got a TLS problem that I'm trying to figure out.

```
Traceback (most recent call last):
  File "bin/pip", line 7, in <module>
    from pip import main
  File "/Users/kim/PloneBuilds/castle.cms/lib/python2.7/site-packages/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/Users/kim/PloneBuilds/castle.cms/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 10, in <module>
    from pip.download import path_to_url
  File "/Users/kim/PloneBuilds/castle.cms/lib/python2.7/site-packages/pip/download.py", line 18, in <module>
    import ssl  # noqa
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 133, in <module>
    PROTOCOL_SSLv23 = PROTOCOL_TLS
NameError: name 'PROTOCOL_TLS' is not defined
```
Decided to try it on Ubuntu 16.04 too where I ran into a problem building cryptography:
```
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
  build/temp.linux-x86_64-2.7/_openssl.c:729:6: error: conflicting types for ‘BIO_new_mem_buf’
   BIO *BIO_new_mem_buf(void *, int);
        ^
  In file included from /usr/include/openssl/asn1.h:65:0,
                   from build/temp.linux-x86_64-2.7/_openssl.c:445:
  /usr/include/openssl/bio.h:692:6: note: previous declaration of ‘BIO_new_mem_buf’ was here
   BIO *BIO_new_mem_buf(const void *buf, int len);
        ^
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for cryptography
```

**Comment by tkimnguyen** [comment]
OK on another Mac I was able to get things running. Will post details; the steps weren't quite obvious.

**Comment by davisagli** [comment]
What I gathered from looking at `cryptography`'s documentation is that installation works best when pip can install a prebuilt wheel rather than building it from scratch. So maybe a wheel isn't available for the version of the lib that I put in requirements.txt on particular versions of macOS, and on ubuntu.

**Comment by tkimnguyen** [comment]
On my original Mac, the problem was a bad virtualenv. Once I `rm -r bin lib` and ran `virtualenv -p python2.7 .` the `bin/pip install -r requirements.txt` completed and then so did `bin/buildout`

**Comment by tkimnguyen** [comment]
Thanks again, @davisagli !

**Pull request merged**
